version: '2'
services:

 influx:
  image: registry.sonata-nfv.eu:5000/son-monitor-influxdb
  restart: always
  ports:
   - "8087:8086"

 mysql:
  image: registry.sonata-nfv.eu:5000/son-monitor-mysql
  restart: always
  ports:
   - 3306

 pushgateway:
  image: registry.sonata-nfv.eu:5000/son-monitor-pushgateway
  restart: always
  ports:
   - "9091:9091"

 prometheus:
  image: registry.sonata-nfv.eu:5000/son-monitor-prometheus
  restart: always
  ports:
   - "9090:9090"
  depends_on:
   - pushgateway
   - influx

 manager:
  image: registry.sonata-nfv.eu:5000/son-monitor-manager
  restart: unless-stopped
  ports:
   - "8000:8000"
  depends_on:
   - mysql
