global:
  evaluation_interval: 15s
  external_labels: {monitor: sonata-monitor}
  scrape_interval: 15s
rule_files: [/opt/Monitoring/prometheus/rules/alert.rules,/opt/Monitoring/prometheus/rules/NF777777.rules]
scrape_configs:
- job_name: sonata
  scrape_interval: 15s
  scrape_timeout: 5s
  target_groups:
  - labels: {group: development}
    targets: ['192.168.1.89:8080', '192.168.1.46:9100', '192.168.1.70:9091', '192.168.1.39:9100','192.168.1.39:9090', 'pushgateway:9091']
